Update ec2-linux-cli-scripts

diff --git a/ec2-linux-cli-scripts b/ec2-linux-cli-scripts
--- a/ec2-linux-cli-scripts
+++ b/ec2-linux-cli-scripts
@@ -1,9 +1,13 @@
 # Environment: AWS CLI, Bash, Amazon Linux, 
 
+# Task: a must settings for bash script debugging.
+
+set -o errexit  # abort on nonzero exitstatus
+set -o pipefail # don't hide errors within pipes
 
 # TASK: Check if user has AWS credentials from EC2 by running command: aws sts get-caller-identity
 
-prompt >> aws sts get-caller-identity
+aws sts get-caller-identity
 {
     "Account": "123456789012",
     "UserId": "XKIAIV4QH8DVBZXDMKQE",
@@ -19,12 +23,11 @@ Above example requires the jq package
 
 # TASK: Using the CLI and Bash and EC2 metadata call, determine AWS region
 
-prompt >> MY_AWS_REGIONS=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/\(.*\)[a-z]/\1/')
-
+MY_AWS_REGIONS=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/\(.*\)[a-z]/\1/')
 
 # TASK: Using the variable MY_AWS_REGIONS from previous command, we can test if we are in our supported regions
 
-prompt >> SUPPORTED_REGIONS=("us-east-1" "us-east-2" )
+SUPPORTED_REGIONS=("us-east-1" "us-east-2" )
 if [[ ! " ${SUPPORTED_REGIONS[@]} " =~ " ${MY_AWS_REGIONS} " ]]; then
     /bin/echo -e "'$MY_AWS_REGIONS' is not a supported AWS Region." 
 else
@@ -34,7 +37,18 @@ fi
 
 # TASK: Return a physical resource id from a CloudFormation stack and assign to a variable. In this example, return the name of an S3 bucket.
 
-prompt>> MY_BUCKET=$(aws cloudformation describe-stack-resource --stack-name my-stack --logical-resource-id bucket --query "StackResourceDetail.PhysicalResourceId" --output text)
+MY_BUCKET=$(aws cloudformation describe-stack-resource --stack-name my-stack --logical-resource-id bucket --query "StackResourceDetail.PhysicalResourceId" --output text)
 
 echo $MY_BUCKET
 
+# TASK: Return AWS endpoint address of a service resource. In this example, return an ATS signed data endpint.
+
+MY_ENDPOINT_HOST=$(aws iot describe-endpoint --endpoint-type iot:Data-ATS | grep endpointAddress | cut -d'"' -f 4)
+
+# Task: Return the IAM Role of a resouces in a CloudFormation stack. The example below returns the role of a Lambda function
+
+MY_LAMBDA_ROLE=$(aws cloudformation describe-stack-resource --stack-name my-stack --logical-resource-id MyLambdaRole --query "StackResourceDetail.PhysicalResourceId" --output text)
+
+# Task: Return the ARN of an IAM Role.
+
+MY_LAMBDA_ROLE_ARN=$(aws iam get-role --role-name $MY_LAMBDA_ROLE | grep Arn | cut -d'"' -f 4)
